### ISSUE TITLE
Date abbreviations (e.g. '16 for 2016) not recognized

### ISSUE THREAD

**Issue by james-bostock** [gitenberg-dev/punctuation-cleanup#5]
Date abbreviations of the form 'YY are not recognized. A concrete example is from the author's note to Joseph Conrad's 'Nostromo' where we see:

"As a matter of fact in 1875 or '6, when very young, in the West Indies"

I believe adding the following at the end of replacements.jsb fixes the issue:

{ searchFor: /(\s)'(\d+)/g, replaceWith: "$1’$2"}

**Comment by eshellman** [comment]
seems correct. Can you try it out?

**Comment by james-bostock** [comment]
Sure. If I run both the current version and a version modified as I suggest above on pg2021.txt (Conrad's 'Nostromo'), the only line in the output that differs is the one that I quote from the author's note.
[pg2021-new.txt](https://github.com/gitenberg-dev/punctuation-cleanup/files/104157/pg2021-new.txt)
[pg2021-old.txt](https://github.com/gitenberg-dev/punctuation-cleanup/files/104158/pg2021-old.txt)

**Comment by eshellman** [comment]
could you try it on at least one more text and then submit a PR? thanks!

**Comment by james-bostock** [comment]
Done!

**Comment by eshellman** [comment]
fixed in PR #6
